# Generated by Django 5.2.17 on 2026-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_organization_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dismissal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dismissed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Ishda'), ('on_leave', "Ta'tilda"), ('dismissed', "Ishdan bo'shagan")], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='hired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
