# Generated by Django 5.2.17 on 2026-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_firm_moderation_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmfine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='firmmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='firmmoderationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='firmreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
