# Generated by Django 4.2.7 on 2026-09-24 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_backfill_default_organization"),
        ("orders", "0005_organization_tenancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commission_rate_applied",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="location_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="location_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="platform_share",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.CreateModel(
            name="OrderEscrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "To'lov kutilmoqda"),
                            ("held", "Ushlab turilgan"),
                            ("released", "Firmaga o'tkazilgan"),
                            ("refunded", "Qaytarilgan"),
                            ("disputed", "Nizoli"),
                            ("frozen", "Muzlatilgan"),
                        ],
                        db_index=True,
                        default="awaiting_payment",
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="UZS", max_length=8)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "firm_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("disputed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("dispute_reason", models.TextField(blank=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma escrow",
                "verbose_name_plural": "Buyurtma escrowlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("escrow_hold", "Escrow ushlash"),
                            ("escrow_release", "Escrow chiqarish"),
                            ("platform_fee", "Platforma ulushi"),
                            ("refund", "Qaytarish"),
                            ("fine", "Jarima"),
                            ("debt_adjust", "Qarz tuzatish"),
                            ("punishment", "Jazo"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="UZS", max_length=8)),
                ("debit_account", models.CharField(blank=True, max_length=64)),
                ("credit_account", models.CharField(blank=True, max_length=64)),
                ("note", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "escrow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="orders.orderescrow",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="organizations.organization",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger yozuvi",
                "verbose_name_plural": "Ledger yozuvlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
