# Generated by Django 5.2.17 on 2026-10-01 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_commission_rate_applied_order_location_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], max_length=16)),
                ('status', models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('submitted', 'Tekshirilmoqda'), ('confirmed', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('checkout_url', models.URLField(blank=True, max_length=1024)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Buyurtma to'lovi",
                'verbose_name_plural': "Buyurtma to'lovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
