# Generated by Django 5.2.17 on 2026-10-01 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_service_base_service_service_moderated_at_and_more'),
        ('orders', '0007_orderpayment'),
        ('organizations', '0004_organization_facebook_organization_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eta_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='work_stage',
            field=models.CharField(blank=True, choices=[('accepted', 'Ishchi guruh qabul qildi'), ('on_the_way', "Yo'lga chiqdi"), ('arrived', 'Yetib keldi'), ('working', 'Ishlayapti'), ('finished', 'Ishni tugatdi')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='work_stage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='stage',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='orders_orde_organiz_af13c0_idx'),
        ),
    ]
