# Generated by Django 5.2.17 on 2026-10-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_distance_km_order_eta_at_order_eta_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='provider',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('test', "Sinov to'lovi")], max_length=16),
        ),
    ]
