# Generated by Django 5.2.17 on 2026-10-04 11:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_items(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    OrderItem.objects.bulk_create(
        [
            OrderItem(order_id=order.pk, service_id=order.service_id, amount=order.quoted_price)
            for order in Order.objects.only("pk", "service_id", "quoted_price").iterator()
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_service_base_service_service_moderated_at_and_more"),
        ("orders", "0009_orderpayment_test_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.service",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "service"), name="uniq_order_item_service"
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_items, migrations.RunPython.noop),
    ]
