# Generated by Django 4.2.7 on 2026-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_tenancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loyalty_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
