# Generated by Django 5.2.17 on 2026-09-17 09:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_firm_share'),
        ('staff', '0005_escrow_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('awaiting_payment', "To'lov kutilmoqda"), ('held', 'E-Makonda ushlab turilgan'), ('released', "Firmaga o'tkazilgan"), ('refunded', 'Userga qaytarilgan'), ('disputed', 'Nizoli'), ('frozen', 'Muzlatilgan')], db_index=True, default='awaiting_payment', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('commission_rate', models.DecimalField(decimal_places=1, default=Decimal('0.3'), max_digits=3)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('firm_payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_actions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders.order')),
            ],
            options={
                'verbose_name': 'Escrow',
                'verbose_name_plural': 'Escrowlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('escrow_in', 'User → E-Makon (escrow)'), ('escrow_release', 'E-Makon → Firma'), ('escrow_refund', 'E-Makon → User (qaytarish)'), ('commission', 'Platforma ulushi'), ('fine', 'Jarima'), ('rate_hike', 'Foiz oshirildi'), ('subscription', 'Obuna'), ('debt_adjust', 'Qarz tuzatish'), ('punish_firm', 'Firma jazolandi'), ('punish_user', 'User jazolandi'), ('dispute', 'Nizo'), ('adjustment', 'Tuzatish')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('debit_account', models.CharField(choices=[('user', 'Foydalanuvchi'), ('platform_escrow', 'E-Makon escrow'), ('platform_revenue', 'E-Makon daromad'), ('firm_payable', "Firmaga to'lov"), ('firm_debt', 'Firma qarzi')], max_length=32)),
                ('credit_account', models.CharField(choices=[('user', 'Foydalanuvchi'), ('platform_escrow', 'E-Makon escrow'), ('platform_revenue', 'E-Makon daromad'), ('firm_payable', "Firmaga to'lov"), ('firm_debt', 'Firma qarzi')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_created', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='staff.partnerfirm')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.orderescrow')),
            ],
            options={
                'verbose_name': 'Hisob yozuvi',
                'verbose_name_plural': 'Hisob yozuvlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry_type', 'created_at'], name='finance_led_entry_t_ef2d5e_idx'), models.Index(fields=['firm', 'created_at'], name='finance_led_firm_id_7390ad_idx')],
            },
        ),
    ]
