# Generated by Django 4.2.7 on 2026-09-24 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0005_organization_tenancy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, default="redeem", max_length=64)),
                ("points_cost", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Mukofot",
                "verbose_name_plural": "Mukofotlar",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uzs_per_point", models.PositiveIntegerField(default=10000)),
                ("min_redeem_points", models.PositiveIntegerField(default=50)),
                ("expire_months", models.PositiveIntegerField(default=12)),
            ],
            options={
                "verbose_name": "Sodiqlik sozlamalari",
                "verbose_name_plural": "Sodiqlik sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earn", "Hisobga olindi"),
                            ("redeem", "Almashtirildi"),
                            ("expire", "Muddati o'tdi"),
                            ("adjust", "Tuzatish"),
                        ],
                        max_length=16,
                    ),
                ),
                ("points", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=512)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ball tranzaksiyasi",
                "verbose_name_plural": "Ball tranzaksiyalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
