# Generated by Django 5.2.17 on 2026-08-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_weekdays', models.JSONField(blank=True, default=list)),
                ('area_size', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Tugagan'), ('cancelled', 'Bekor')], default='active', max_length=16)),
                ('assigned_workers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'worker'}, related_name='care_contracts_assigned', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_contracts', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_contract', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('reminded', 'Eslatma yuborildi'), ('approved', 'Tasdiqlangan'), ('postponed', 'Kechiktirilgan'), ('done', 'Bajarildi'), ('not_done', 'Bajarilmadi'), ('rejected', 'Rad etilgan'), ('awaiting_report', 'Hisobot kutilmoqda')], default='scheduled', max_length=20)),
                ('assigned_worker_name', models.CharField(blank=True, max_length=255)),
                ('report_notes', models.TextField(blank=True)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='care.carecontract')),
                ('planned_worker', models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_care_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['visit_date', 'id'],
                'indexes': [models.Index(fields=['visit_date', 'status'], name='care_carevi_visit_d_e16c2c_idx')],
            },
        ),
    ]
