# Generated by Django 5.2.15 on 2026-09-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care", "0001_initial"),
        ("organizations", "0001_organization_tenancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="carecontract",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_contracts",
                to="organizations.organization",
            ),
        ),
    ]
