# Generated by Django 5.2.17 on 2026-10-01 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_organization_tenancy'),
        ('catalog', '0006_service_base_service_service_moderated_at_and_more'),
        ('orders', '0008_order_distance_km_order_eta_at_order_eta_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carecontract',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_contracts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='client_type',
            field=models.CharField(choices=[('household', "Uy xo'jaligi"), ('organization', 'Tashkilot / markaz')], default='household', max_length=16),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_contracts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='currency',
            field=models.CharField(default='UZS', max_length=8),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Haftalik'), ('biweekly', '2 haftada bir'), ('monthly', 'Oylik')], default='weekly', max_length=16),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='payment_terms',
            field=models.CharField(choices=[('monthly', 'Har oy'), ('quarterly', 'Har chorak'), ('upfront', "Oldindan to'liq")], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='platform_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='price_per_visit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_contracts', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carecontract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='carecontract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carecontract',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_contract', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='carecontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending', "Tizim tasdig'ida"), ('active', 'Faol'), ('paused', "To'xtatilgan"), ('completed', 'Tugagan'), ('cancelled', 'Bekor'), ('rejected', 'Rad etilgan')], db_index=True, default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='CareContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_contract_events', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='care.carecontract')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
