# Generated by Django 5.2.15 on 2026-09-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_service_mobile_fields"),
        ("organizations", "0001_organization_tenancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="catalog_service_org_slug_uniq"
            ),
        ),
    ]
