# Generated by Django 5.2.17 on 2026-10-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
