# Generated by Django 5.2.17 on 2026-10-01 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_service_price_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_service',
            field=models.ForeignKey(blank=True, help_text="Katalogdagi xizmat turi; firma taklifi shu turga bog'lanadi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Tekshiruvda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='approved', max_length=16),
        ),
    ]
