# Generated by Django 5.2.15 on 2026-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "Tashkilot",
                "verbose_name_plural": "Tashkilotlar",
                "ordering": ["name", "id"],
            },
        ),
    ]
