# Generated by Django 4.2.7 on 2026-09-24 03:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0006_order_commission_rate_applied_order_location_lat_and_more"),
        ("organizations", "0002_backfill_default_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=512)),
                (
                    "investment_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("currency", models.CharField(default="UZS", max_length=8)),
                (
                    "share_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("pending", "Kutilmoqda"),
                            ("ended", "Tugagan"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("exit_reason", models.TextField(blank=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Investor",
                "verbose_name_plural": "Investorlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.30"),
                help_text="Platforma ulushi foizda (0.1–3)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("3")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="debt_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="debt_currency",
            field=models.CharField(default="UZS", max_length=8),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="district",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="exit_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="location_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="location_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ratings_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="organization",
            name="region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="organization",
            name="sales_banned_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("general", "Umumiy"),
                    ("landscape", "Landshaft"),
                    ("garden_care", "Bog' parvarishi"),
                    ("ornamental", "Manzarali o'simliklar"),
                    ("irrigation", "Sug'orish"),
                    ("pest_control", "Dorilash"),
                ],
                default="general",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Faol"),
                    ("pending", "Kutilmoqda"),
                    ("suspended", "Bloklangan"),
                    ("ended", "Tugagan"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_plan",
            field=models.CharField(
                choices=[("none", "Yo'q"), ("monthly", "Oylik"), ("yearly", "Yillik")],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_units",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="unpaid_fines",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="warnings_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FirmReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="organizations.organization",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firm_reviews",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma sharhi",
                "verbose_name_plural": "Firma sharhlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirmModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firm_moderation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma moderatsiya logi",
                "verbose_name_plural": "Firma moderatsiya loglari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirmMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("message", "Xabar"),
                            ("warning", "Ogohlantirish"),
                            ("report", "Hisobot"),
                        ],
                        default="message",
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="organizations.organization",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firm_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma xabari",
                "verbose_name_plural": "Firma xabarlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirmFine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="UZS", max_length=8)),
                ("reason", models.CharField(blank=True, max_length=512)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firm_fines_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma jarimasi",
                "verbose_name_plural": "Firma jarimalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
