# Generated by Django 5.2.17 on 2026-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_investor_organization_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='telegram_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='work_hours',
            field=models.CharField(blank=True, default='09:00 – 18:00', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
