# Generated by Django 5.2.17 on 2026-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_bot_mvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdelivery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
